services:
  tiles-processor:
    container_name: tiles-processor-dev-container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${DATA_DIR_HOST}:${DATA_DIR_CONTAINER}
      - ./settings.json:/app/settings.json:ro
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
      - DATA_DIR_CONTAINER=${DATA_DIR_CONTAINER}
