services:
  tiles-processor:
    image: tiles-processor
    container_name: tiles-processor-container
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - LOG_LEVEL=${LOG_LEVEL}
        - DATA_DIR_CONTAINER=/app/data
    volumes:
      - tiles_data:/app/data
      - ./settings.json:/app/settings.json:ro
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
      - DATA_DIR_CONTAINER=/app/data
    healthcheck:
      test: ["CMD", "python3", "/app/src/healthcheck.py", "||", "exit", "1"]
      interval: 2s
      timeout: 10s
      retries: 3

volumes:
  tiles_data:
    external: true
