services:
  tiles-processor:
    build:
      context: .
      dockerfile: Dockerfile
    image: tiles-processor
    container_name: tiles-processor-container
    volumes:
      - ./.tmp:/app/.tmp
    # Options: process_band_13 or process_band_9
    command: python3 src/main.py process_band_13
