services:
  tiles-processor:
    container_name: tiles-processor-dev-container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${TMP_DIR_HOST}:${TMP_DIR_CONTAINER}
      - ${SCHEDULER_DB_HOST_DIR}:${SCHEDULER_DB_CONTAINER_DIR}
      - ./settings.json:/app/settings.json:ro
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
      - TMP_DIR_CONTAINER=${TMP_DIR_CONTAINER}
      - SCHEDULER_DB_PATH=${SCHEDULER_DB_PATH}
