#!/bin/bash
#
# Generate docker-compose.yaml with a configurable number of workers.
#
# Usage:
#   ./scripts/generate-compose.sh [--dev] [--light <N>] <num_workers> [output_file]
#
# Arguments:
#   --dev        - Generate dev configuration (bind mounts, lower retries)
#   --light <N>  - Number of light workers (consume the light queue); default 0
#   num_workers  - Number of normal worker containers (required, must be >= 1)
#   output_file  - Output filename (optional, default based on mode)
#
# Examples:
#   ./scripts/generate-compose.sh 5                          # 5 normal workers -> docker-compose.yaml (prod)
#   ./scripts/generate-compose.sh --light 4 2                # 2 normal + 4 light -> docker-compose.yaml (prod)
#   ./scripts/generate-compose.sh --dev --light 4 2          # 2 normal + 4 light -> docker-compose-dev.yaml
#   ./scripts/generate-compose.sh 3 docker-compose-prod.yaml # 3 normal workers -> docker-compose-prod.yaml
#
# NOTE: the checked-in docker-compose.yaml / docker-compose-dev.yaml are HAND-EDITED
# beyond what this template emits (pinned RustFS tag, console port, CORS, input-S3
# credentials, settings.json mount). They are the authoritative files — edit them
# directly. Regenerating will NOT reproduce those manual edits verbatim.
#

set -e

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m' # No Color

# Parse flags (--dev, --light <N>) in any order before positionals
DEV_MODE=false
NUM_LIGHT_WORKERS=0
while [ $# -gt 0 ]; do
    case "$1" in
        --dev)
            DEV_MODE=true
            shift
            ;;
        --light)
            NUM_LIGHT_WORKERS="$2"
            shift 2
            ;;
        *)
            break
            ;;
    esac
done

# Validate arguments
if [ -z "$1" ]; then
    echo -e "${RED}Error: Number of workers is required${NC}" >&2
    echo "Usage: $0 [--dev] [--light <N>] <num_workers> [output_file]" >&2
    echo "" >&2
    echo "Options:" >&2
    echo "  --dev        Generate dev configuration (bind mounts, lower retries)" >&2
    echo "  --light <N>  Number of light workers (consume the light queue); default 0" >&2
    exit 1
fi

NUM_WORKERS="$1"

# Set default output file based on mode
if [ "$DEV_MODE" = true ]; then
    OUTPUT_FILE="${2:-docker-compose-dev.yaml}"
else
    OUTPUT_FILE="${2:-docker-compose.yaml}"
fi

# Validate num_workers is a positive integer
if ! [[ "$NUM_WORKERS" =~ ^[1-9][0-9]*$ ]]; then
    echo -e "${RED}Error: num_workers must be a positive integer (got: $NUM_WORKERS)${NC}" >&2
    exit 1
fi

# Validate num_light_workers is a non-negative integer (0 disables the light pool)
if ! [[ "$NUM_LIGHT_WORKERS" =~ ^[0-9]+$ ]]; then
    echo -e "${RED}Error: --light must be a non-negative integer (got: $NUM_LIGHT_WORKERS)${NC}" >&2
    exit 1
fi

# Set mode-specific variables
if [ "$DEV_MODE" = true ]; then
    MODE_LABEL="dev"
    RUSTFS_CONTAINER_NAME="tiles-processor-dev-rustfs"
    RUSTFS_INIT_CONTAINER_NAME="tiles-processor-dev-rustfs-init"
    RABBITMQ_VOLUME="rabbitmq_dev_data"
    # Dev: host bind mount + run as host user so files are debuggable (owned by you).
    RUSTFS_DATA_VOLUME="./data_rustfs:/data"
    RUSTFS_USER_LINE='    user: "${RUSTFS_UID:-1000}:${RUSTFS_GID:-1000}"'
    APP_DATA_VOLUME="./data:\${DATA_DIR}"
    RABBITMQ_RETRIES="10"
    RUSTFS_RETRIES="10"
    APP_RETRIES="3"
else
    MODE_LABEL="prod"
    RUSTFS_CONTAINER_NAME="tiles-processor-rustfs"
    RUSTFS_INIT_CONTAINER_NAME="tiles-processor-rustfs-init"
    RABBITMQ_VOLUME="rabbitmq_data"
    # Prod: named volume + image default user (UID 10001); no user override.
    RUSTFS_DATA_VOLUME="rustfs_data:/data"
    RUSTFS_USER_LINE=""
    APP_DATA_VOLUME="tiles_data:/app/data"
    RABBITMQ_RETRIES="10"
    RUSTFS_RETRIES="10"
    APP_RETRIES="20"
fi

echo -e "${YELLOW}Mode: ${MODE_LABEL}${NC}"
echo "Generating docker-compose with $NUM_WORKERS worker(s) + $NUM_LIGHT_WORKERS light worker(s) -> $OUTPUT_FILE"

# Generate the docker-compose file
cat > "$OUTPUT_FILE" << HEADER
# Auto-generated docker-compose file (${MODE_LABEL})
# Generated by: scripts/generate-compose.sh
#
# To regenerate with different number of workers:
#   ./scripts/generate-compose.sh $([ "$DEV_MODE" = true ] && echo "--dev ")$([ "$NUM_LIGHT_WORKERS" -gt 0 ] && echo "--light ${NUM_LIGHT_WORKERS} ")${NUM_WORKERS} ${OUTPUT_FILE}

services:
  # RabbitMQ message broker for the work queue
  rabbitmq:
    image: rabbitmq:4.2.2-management
    container_name: tiles-processor-rabbitmq
    ports:
      - "\${RABBITMQ_PORT}:5672"      # AMQP protocol
      - "\${RABBITMQ_MGMT_PORT}:15672"  # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: \${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: \${RABBITMQ_PASSWORD}

      # Reduce CPU usage by disabling Erlang scheduler busy-wait tuning.
      # These settings are beneficial for low-throughput or idle-heavy workloads,
      # where minimizing background CPU wakeups is more important than latency.
      # +sbwt none       # Disable scheduler busy wait thresholds
      # +sbwtdcpu none   # Disable busy wait tuning for CPU-bound schedulers
      # +sbwtdio none    # Disable busy wait tuning for I/O-bound schedulers
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: >
        +sbwt none
        +sbwtdcpu none
        +sbwtdio none
    volumes:
      - ${RABBITMQ_VOLUME}:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 30s
      timeout: 10s
      retries: ${RABBITMQ_RETRIES}
      start_period: 15s
      start_interval: 1s

  # S3-compatible object storage
  rustfs:
    image: rustfs/rustfs:1.0.0-beta.8
    container_name: ${RUSTFS_CONTAINER_NAME}
${RUSTFS_USER_LINE}
    stop_grace_period: 30s
    ports:
      - "\${S3_TILES_DATA_PORT}:9000"          # S3 API
      - "\${RUSTFS_CONSOLE_PORT:-9001}:9001"   # Console UI
    environment:
      - RUSTFS_VOLUMES=/data
      - RUSTFS_ADDRESS=0.0.0.0:9000
      - RUSTFS_CONSOLE_ADDRESS=0.0.0.0:9001
      - RUSTFS_CONSOLE_ENABLE=true
      - RUSTFS_ACCESS_KEY=\${RUSTFS_ACCESS_KEY}
      - RUSTFS_SECRET_KEY=\${RUSTFS_SECRET_KEY}
      - RUSTFS_CORS_ALLOWED_ORIGINS=\${RUSTFS_CORS_ALLOWED_ORIGINS:-*}
      - RUSTFS_CONSOLE_CORS_ALLOWED_ORIGINS=\${RUSTFS_CONSOLE_CORS_ALLOWED_ORIGINS:-*}
    volumes:
      - ${RUSTFS_DATA_VOLUME}
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:9000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: ${RUSTFS_RETRIES}
      start_period: 20s
      start_interval: 2s

  # One-shot bucket bootstrap: creates the three buckets via the standard S3 API
  # (aws-cli, path-style; head-bucket-or-create makes it idempotent on restart).
  rustfs-init:
    image: amazon/aws-cli:latest
    container_name: ${RUSTFS_INIT_CONTAINER_NAME}
    depends_on:
      rustfs:
        condition: service_healthy
    environment:
      - AWS_ACCESS_KEY_ID=\${RUSTFS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=\${RUSTFS_SECRET_KEY}
      - AWS_DEFAULT_REGION=us-east-1
      - S3_TILES_DATA_BUCKET_NAME=\${S3_TILES_DATA_BUCKET_NAME}
      - S3_INTERSECTION_DATA_BUCKET_NAME=\${S3_INTERSECTION_DATA_BUCKET_NAME}
      - S3_BASEMAP_BUCKET_NAME=\${S3_BASEMAP_BUCKET_NAME}
    entrypoint: ["/bin/sh", "-c"]
    command:
      - >
        aws configure set default.s3.addressing_style path &&
        for b in "\$\$S3_TILES_DATA_BUCKET_NAME" "\$\$S3_INTERSECTION_DATA_BUCKET_NAME" "\$\$S3_BASEMAP_BUCKET_NAME"; do
        aws --endpoint-url http://rustfs:9000 s3api head-bucket --bucket "\$\$b" 2>/dev/null ||
        aws --endpoint-url http://rustfs:9000 s3 mb "s3://\$\$b";
        done
    restart: "no"

  # Producer - discovers new images and publishes work units
  # Runs continuously with APScheduler (every 5 minutes)
  producer:
    image: tiles-processor
    container_name: tiles-processor-producer
    depends_on:
      rabbitmq:
        condition: service_healthy
      rustfs-init:
        condition: service_completed_successfully
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 src/main.py producer
    volumes:
      - ${APP_DATA_VOLUME}
      - ./settings.json:/app/settings.json:ro
    environment:
      - LOG_LEVEL=\${LOG_LEVEL}
      - DATA_DIR=\${DATA_DIR}
      - S3_TILES_DATA_ENDPOINT=rustfs:9000
      - S3_TILES_DATA_BUCKET_NAME=\${S3_TILES_DATA_BUCKET_NAME}
      - S3_TILES_DATA_SECURE=false
      - S3_TILES_DATA_TILES_PROCESSOR_USER=\${S3_TILES_DATA_TILES_PROCESSOR_USER}
      - S3_TILES_DATA_TILES_PROCESSOR_PASSWORD=\${S3_TILES_DATA_TILES_PROCESSOR_PASSWORD}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=\${RABBITMQ_PORT}
      - RABBITMQ_USER=\${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=\${RABBITMQ_PASSWORD}
      - RABBITMQ_QUEUE=\${RABBITMQ_QUEUE}
      - RABBITMQ_RADAR_LIGHT_QUEUE=\${RABBITMQ_RADAR_LIGHT_QUEUE}
      - RABBITMQ_WRF_LIGHT_QUEUE=\${RABBITMQ_WRF_LIGHT_QUEUE}
      - RABBITMQ_DLQ=\${RABBITMQ_DLQ}
      - RABBITMQ_DLX=\${RABBITMQ_DLX}
      - JOB_TTL_MINUTES=\${JOB_TTL_MINUTES}
      - GDAL_CACHEMAX=\${GDAL_CACHEMAX}
      - CPL_VSIL_CURL_CACHE_SIZE=\${CPL_VSIL_CURL_CACHE_SIZE}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8080/health')"]
      interval: 10s
      timeout: 10s
      retries: ${APP_RETRIES}
      start_period: 15s
      start_interval: 1s

HEADER

# Generate worker services
for i in $(seq 1 "$NUM_WORKERS"); do
    cat >> "$OUTPUT_FILE" << WORKER
  # Worker ${i} - processes work units from the queue
  worker${i}:
    image: tiles-processor
    container_name: tiles-processor-worker${i}
    depends_on:
      rabbitmq:
        condition: service_healthy
      rustfs-init:
        condition: service_completed_successfully
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 src/main.py worker
    volumes:
      - ${APP_DATA_VOLUME}
      - ./settings.json:/app/settings.json:ro
    environment:
      - WORKER_ID=worker${i}
      - LOG_LEVEL=\${LOG_LEVEL}
      - DATA_DIR=\${DATA_DIR}
      - S3_TILES_DATA_ENDPOINT=rustfs:9000
      - S3_TILES_DATA_BUCKET_NAME=\${S3_TILES_DATA_BUCKET_NAME}
      - S3_TILES_DATA_SECURE=false
      - S3_TILES_DATA_TILES_PROCESSOR_USER=\${S3_TILES_DATA_TILES_PROCESSOR_USER}
      - S3_TILES_DATA_TILES_PROCESSOR_PASSWORD=\${S3_TILES_DATA_TILES_PROCESSOR_PASSWORD}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=\${RABBITMQ_PORT}
      - RABBITMQ_USER=\${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=\${RABBITMQ_PASSWORD}
      - RABBITMQ_QUEUE=\${RABBITMQ_QUEUE}
      - RABBITMQ_RADAR_LIGHT_QUEUE=\${RABBITMQ_RADAR_LIGHT_QUEUE}
      - RABBITMQ_WRF_LIGHT_QUEUE=\${RABBITMQ_WRF_LIGHT_QUEUE}
      - RABBITMQ_DLQ=\${RABBITMQ_DLQ}
      - RABBITMQ_DLX=\${RABBITMQ_DLX}
      - JOB_TTL_MINUTES=\${JOB_TTL_MINUTES}
      - GDAL_CACHEMAX=\${GDAL_CACHEMAX}
      - CPL_VSIL_CURL_CACHE_SIZE=\${CPL_VSIL_CURL_CACHE_SIZE}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8080/health')"]
      interval: 10s
      timeout: 10s
      retries: ${APP_RETRIES}
      start_period: 15s
      start_interval: 1s

WORKER
done

# Generate light worker services (consume the light queue: radar/WRF)
for i in $(seq 1 "$NUM_LIGHT_WORKERS"); do
    cat >> "$OUTPUT_FILE" << LIGHT_WORKER
  # Light worker ${i} - processes lightweight units (radar/WRF) from the light queue
  worker-light${i}:
    image: tiles-processor
    container_name: tiles-processor-worker-light${i}
    depends_on:
      rabbitmq:
        condition: service_healthy
      rustfs-init:
        condition: service_completed_successfully
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 src/main.py worker
    volumes:
      - ${APP_DATA_VOLUME}
      - ./settings.json:/app/settings.json:ro
    environment:
      - WORKER_ID=worker-light${i}
      - LOG_LEVEL=\${LOG_LEVEL}
      - DATA_DIR=\${DATA_DIR}
      - S3_TILES_DATA_ENDPOINT=rustfs:9000
      - S3_TILES_DATA_BUCKET_NAME=\${S3_TILES_DATA_BUCKET_NAME}
      - S3_TILES_DATA_SECURE=false
      - S3_TILES_DATA_TILES_PROCESSOR_USER=\${S3_TILES_DATA_TILES_PROCESSOR_USER}
      - S3_TILES_DATA_TILES_PROCESSOR_PASSWORD=\${S3_TILES_DATA_TILES_PROCESSOR_PASSWORD}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=\${RABBITMQ_PORT}
      - RABBITMQ_USER=\${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=\${RABBITMQ_PASSWORD}
      - RABBITMQ_QUEUE=\${RABBITMQ_QUEUE}
      - WORKER_TYPE=light
      - RABBITMQ_RADAR_LIGHT_QUEUE=\${RABBITMQ_RADAR_LIGHT_QUEUE}
      - RABBITMQ_WRF_LIGHT_QUEUE=\${RABBITMQ_WRF_LIGHT_QUEUE}
      - RABBITMQ_DLQ=\${RABBITMQ_DLQ}
      - RABBITMQ_DLX=\${RABBITMQ_DLX}
      - JOB_TTL_MINUTES=\${JOB_TTL_MINUTES}
      - GDAL_CACHEMAX=\${GDAL_CACHEMAX}
      - CPL_VSIL_CURL_CACHE_SIZE=\${CPL_VSIL_CURL_CACHE_SIZE}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8080/health')"]
      interval: 10s
      timeout: 10s
      retries: ${APP_RETRIES}
      start_period: 15s
      start_interval: 1s

LIGHT_WORKER
done

# Generate metrics-api service (read-only status-metrics HTTP API)
cat >> "$OUTPUT_FILE" << METRICS_API
  # Metrics API - read-only status-metrics HTTP API (powers the /status UI)
  metrics-api:
    image: tiles-processor
    container_name: tiles-processor-metrics-api
    depends_on:
      rabbitmq:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 src/main.py metrics-api
    ports:
      - "\${METRICS_API_PORT:-6020}:6020"
    volumes:
      - ${APP_DATA_VOLUME}
      - ./settings.json:/app/settings.json:ro
    environment:
      - LOG_LEVEL=\${LOG_LEVEL}
      - DATA_DIR=\${DATA_DIR}
      - METRICS_API_PORT=6020
      - METRICS_API_KEY=\${METRICS_API_KEY}
      - S3_TILES_DATA_ENDPOINT=rustfs:9000
      - S3_TILES_DATA_BUCKET_NAME=\${S3_TILES_DATA_BUCKET_NAME}
      - S3_TILES_DATA_SECURE=false
      - S3_TILES_DATA_TILES_PROCESSOR_USER=\${S3_TILES_DATA_TILES_PROCESSOR_USER}
      - S3_TILES_DATA_TILES_PROCESSOR_PASSWORD=\${S3_TILES_DATA_TILES_PROCESSOR_PASSWORD}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=\${RABBITMQ_PORT}
      - RABBITMQ_USER=\${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=\${RABBITMQ_PASSWORD}
      - RABBITMQ_QUEUE=\${RABBITMQ_QUEUE}
      - RABBITMQ_RADAR_LIGHT_QUEUE=\${RABBITMQ_RADAR_LIGHT_QUEUE}
      - RABBITMQ_WRF_LIGHT_QUEUE=\${RABBITMQ_WRF_LIGHT_QUEUE}
      - RABBITMQ_DLQ=\${RABBITMQ_DLQ}
      - RABBITMQ_DLX=\${RABBITMQ_DLX}
      - JOB_TTL_MINUTES=\${JOB_TTL_MINUTES}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:6020/health')"]
      interval: 10s
      timeout: 10s
      retries: ${APP_RETRIES}
      start_period: 15s
      start_interval: 1s

METRICS_API

# Add volumes section
if [ "$DEV_MODE" = true ]; then
    # Dev: RustFS uses a ./data_rustfs bind mount (not a named volume).
    cat >> "$OUTPUT_FILE" << VOLUMES
volumes:
  ${RABBITMQ_VOLUME}:
VOLUMES
else
    cat >> "$OUTPUT_FILE" << VOLUMES
volumes:
  tiles_data:
  rustfs_data:
  ${RABBITMQ_VOLUME}:
VOLUMES
fi

echo -e "${GREEN}Generated $OUTPUT_FILE with $NUM_WORKERS worker(s) + $NUM_LIGHT_WORKERS light worker(s) [${MODE_LABEL}]${NC}"
