#!/bin/bash
#
# Generate docker-compose.yaml with a configurable number of workers.
#
# Usage:
#   ./scripts/generate-compose.sh [--dev] <num_workers> [output_file]
#
# Arguments:
#   --dev        - Generate dev configuration (bind mounts, lower retries)
#   num_workers  - Number of worker containers to generate (required, must be >= 1)
#   output_file  - Output filename (optional, default based on mode)
#
# Examples:
#   ./scripts/generate-compose.sh 5                          # 5 workers -> docker-compose.yaml (prod)
#   ./scripts/generate-compose.sh --dev 2                    # 2 workers -> docker-compose-dev.yaml
#   ./scripts/generate-compose.sh 3 docker-compose-prod.yaml # 3 workers -> docker-compose-prod.yaml
#   ./scripts/generate-compose.sh --dev 3 custom.yaml        # 3 workers -> custom.yaml (dev mode)
#

set -e

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m' # No Color

# Parse --dev flag
DEV_MODE=false
if [ "$1" = "--dev" ]; then
    DEV_MODE=true
    shift
fi

# Validate arguments
if [ -z "$1" ]; then
    echo -e "${RED}Error: Number of workers is required${NC}" >&2
    echo "Usage: $0 [--dev] <num_workers> [output_file]" >&2
    echo "" >&2
    echo "Options:" >&2
    echo "  --dev  Generate dev configuration (bind mounts, lower retries)" >&2
    exit 1
fi

NUM_WORKERS="$1"

# Set default output file based on mode
if [ "$DEV_MODE" = true ]; then
    OUTPUT_FILE="${2:-docker-compose-dev.yaml}"
else
    OUTPUT_FILE="${2:-docker-compose.yaml}"
fi

# Validate num_workers is a positive integer
if ! [[ "$NUM_WORKERS" =~ ^[1-9][0-9]*$ ]]; then
    echo -e "${RED}Error: num_workers must be a positive integer (got: $NUM_WORKERS)${NC}" >&2
    exit 1
fi

# Set mode-specific variables
if [ "$DEV_MODE" = true ]; then
    MODE_LABEL="dev"
    SEAWEEDFS_CONTAINER_NAME="tiles-processor-dev-seaweedfs"
    RABBITMQ_VOLUME="rabbitmq_dev_data"
    SEAWEEDFS_DATA_VOLUME="./data_s3:/data"
    APP_DATA_VOLUME="./data:\${DATA_DIR}"
    RABBITMQ_RETRIES="10"
    SEAWEEDFS_RETRIES="10"
    APP_RETRIES="3"
else
    MODE_LABEL="prod"
    SEAWEEDFS_CONTAINER_NAME="tiles-processor-seaweedfs"
    RABBITMQ_VOLUME="rabbitmq_data"
    SEAWEEDFS_DATA_VOLUME="seaweedfs_data:/data"
    APP_DATA_VOLUME="tiles_data:/app/data"
    RABBITMQ_RETRIES="10"
    SEAWEEDFS_RETRIES="10"
    APP_RETRIES="20"
fi

echo -e "${YELLOW}Mode: ${MODE_LABEL}${NC}"
echo "Generating docker-compose with $NUM_WORKERS worker(s) -> $OUTPUT_FILE"

# Generate the docker-compose file
cat > "$OUTPUT_FILE" << HEADER
# Auto-generated docker-compose file (${MODE_LABEL})
# Generated by: scripts/generate-compose.sh
#
# To regenerate with different number of workers:
#   ./scripts/generate-compose.sh $([ "$DEV_MODE" = true ] && echo "--dev ")${NUM_WORKERS} ${OUTPUT_FILE}

services:
  # RabbitMQ message broker for the work queue
  rabbitmq:
    image: rabbitmq:4.2.2-management
    container_name: tiles-processor-rabbitmq
    ports:
      - "\${RABBITMQ_PORT}:5672"      # AMQP protocol
      - "\${RABBITMQ_MGMT_PORT}:15672"  # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: \${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: \${RABBITMQ_PASSWORD}

      # Reduce CPU usage by disabling Erlang scheduler busy-wait tuning.
      # These settings are beneficial for low-throughput or idle-heavy workloads,
      # where minimizing background CPU wakeups is more important than latency.
      # +sbwt none       # Disable scheduler busy wait thresholds
      # +sbwtdcpu none   # Disable busy wait tuning for CPU-bound schedulers
      # +sbwtdio none    # Disable busy wait tuning for I/O-bound schedulers
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: >
        +sbwt none
        +sbwtdcpu none
        +sbwtdio none
    volumes:
      - ${RABBITMQ_VOLUME}:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 30s
      timeout: 10s
      retries: ${RABBITMQ_RETRIES}
      start_period: 15s
      start_interval: 1s

  # S3-compatible object storage
  seaweedfs:
    image: chrislusf/seaweedfs:latest
    container_name: ${SEAWEEDFS_CONTAINER_NAME}
    entrypoint: /bin/sh
    command: -c "sh /start.sh"
    ports:
      - "\${S3_TILES_DATA_PORT}:8333"      # S3 API
    environment:
      - S3_ROOT_USER=\${S3_ROOT_USER}
      - S3_ROOT_PASSWORD=\${S3_ROOT_PASSWORD}
      - S3_TILES_DATA_BUCKET_NAME=\${S3_TILES_DATA_BUCKET_NAME}
      - S3_TILES_DATA_TILES_PROCESSOR_USER=\${S3_TILES_DATA_TILES_PROCESSOR_USER}
      - S3_TILES_DATA_TILES_PROCESSOR_PASSWORD=\${S3_TILES_DATA_TILES_PROCESSOR_PASSWORD}
      - S3_TILES_DATA_DATA_SERVICE_USER=\${S3_TILES_DATA_DATA_SERVICE_USER}
      - S3_TILES_DATA_DATA_SERVICE_PASSWORD=\${S3_TILES_DATA_DATA_SERVICE_PASSWORD}
    volumes:
      - ${SEAWEEDFS_DATA_VOLUME}
      - ./scripts/seaweedfs_start.sh:/start.sh:ro
    healthcheck:
      test: ["CMD-SHELL", "test -f /tmp/seaweedfs_ready && wget -qO /dev/null http://localhost:9333/cluster/status"]
      interval: 10s
      timeout: 5s
      retries: ${SEAWEEDFS_RETRIES}
      start_period: 30s
      start_interval: 2s

  # Producer - discovers new images and publishes work units
  # Runs continuously with APScheduler (every 5 minutes)
  producer:
    image: tiles-processor
    container_name: tiles-processor-producer
    depends_on:
      rabbitmq:
        condition: service_healthy
      seaweedfs:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 src/main.py producer
    volumes:
      - ${APP_DATA_VOLUME}
      - ./settings.json:/app/settings.json:ro
    environment:
      - LOG_LEVEL=\${LOG_LEVEL}
      - DATA_DIR=\${DATA_DIR}
      - S3_TILES_DATA_ENDPOINT=seaweedfs:8333
      - S3_TILES_DATA_BUCKET_NAME=\${S3_TILES_DATA_BUCKET_NAME}
      - S3_TILES_DATA_SECURE=false
      - S3_TILES_DATA_TILES_PROCESSOR_USER=\${S3_TILES_DATA_TILES_PROCESSOR_USER}
      - S3_TILES_DATA_TILES_PROCESSOR_PASSWORD=\${S3_TILES_DATA_TILES_PROCESSOR_PASSWORD}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=\${RABBITMQ_PORT}
      - RABBITMQ_USER=\${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=\${RABBITMQ_PASSWORD}
      - RABBITMQ_QUEUE=\${RABBITMQ_QUEUE}
      - RABBITMQ_DLQ=\${RABBITMQ_DLQ}
      - RABBITMQ_DLX=\${RABBITMQ_DLX}
      - JOB_TTL_MINUTES=\${JOB_TTL_MINUTES}
      - GDAL_CACHEMAX=\${GDAL_CACHEMAX}
      - CPL_VSIL_CURL_CACHE_SIZE=\${CPL_VSIL_CURL_CACHE_SIZE}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8080/health')"]
      interval: 10s
      timeout: 10s
      retries: ${APP_RETRIES}
      start_period: 15s
      start_interval: 1s

HEADER

# Generate worker services
for i in $(seq 1 "$NUM_WORKERS"); do
    cat >> "$OUTPUT_FILE" << WORKER
  # Worker ${i} - processes work units from the queue
  worker${i}:
    image: tiles-processor
    container_name: tiles-processor-worker${i}
    depends_on:
      rabbitmq:
        condition: service_healthy
      seaweedfs:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 src/main.py worker
    volumes:
      - ${APP_DATA_VOLUME}
      - ./settings.json:/app/settings.json:ro
    environment:
      - LOG_LEVEL=\${LOG_LEVEL}
      - DATA_DIR=\${DATA_DIR}
      - S3_TILES_DATA_ENDPOINT=seaweedfs:8333
      - S3_TILES_DATA_BUCKET_NAME=\${S3_TILES_DATA_BUCKET_NAME}
      - S3_TILES_DATA_SECURE=false
      - S3_TILES_DATA_TILES_PROCESSOR_USER=\${S3_TILES_DATA_TILES_PROCESSOR_USER}
      - S3_TILES_DATA_TILES_PROCESSOR_PASSWORD=\${S3_TILES_DATA_TILES_PROCESSOR_PASSWORD}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=\${RABBITMQ_PORT}
      - RABBITMQ_USER=\${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=\${RABBITMQ_PASSWORD}
      - RABBITMQ_QUEUE=\${RABBITMQ_QUEUE}
      - RABBITMQ_DLQ=\${RABBITMQ_DLQ}
      - RABBITMQ_DLX=\${RABBITMQ_DLX}
      - JOB_TTL_MINUTES=\${JOB_TTL_MINUTES}
      - GDAL_CACHEMAX=\${GDAL_CACHEMAX}
      - CPL_VSIL_CURL_CACHE_SIZE=\${CPL_VSIL_CURL_CACHE_SIZE}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8080/health')"]
      interval: 10s
      timeout: 10s
      retries: ${APP_RETRIES}
      start_period: 15s
      start_interval: 1s

WORKER
done

# Generate metrics-api service (read-only status-metrics HTTP API)
cat >> "$OUTPUT_FILE" << METRICS_API
  # Metrics API - read-only status-metrics HTTP API (powers the /status UI)
  metrics-api:
    image: tiles-processor
    container_name: tiles-processor-metrics-api
    depends_on:
      rabbitmq:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 src/main.py metrics-api
    ports:
      - "\${METRICS_API_PORT:-6020}:6020"
    volumes:
      - ${APP_DATA_VOLUME}
      - ./settings.json:/app/settings.json:ro
    environment:
      - LOG_LEVEL=\${LOG_LEVEL}
      - DATA_DIR=\${DATA_DIR}
      - METRICS_API_PORT=6020
      - METRICS_API_KEY=\${METRICS_API_KEY}
      - S3_TILES_DATA_ENDPOINT=seaweedfs:8333
      - S3_TILES_DATA_BUCKET_NAME=\${S3_TILES_DATA_BUCKET_NAME}
      - S3_TILES_DATA_SECURE=false
      - S3_TILES_DATA_TILES_PROCESSOR_USER=\${S3_TILES_DATA_TILES_PROCESSOR_USER}
      - S3_TILES_DATA_TILES_PROCESSOR_PASSWORD=\${S3_TILES_DATA_TILES_PROCESSOR_PASSWORD}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=\${RABBITMQ_PORT}
      - RABBITMQ_USER=\${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=\${RABBITMQ_PASSWORD}
      - RABBITMQ_QUEUE=\${RABBITMQ_QUEUE}
      - RABBITMQ_DLQ=\${RABBITMQ_DLQ}
      - RABBITMQ_DLX=\${RABBITMQ_DLX}
      - JOB_TTL_MINUTES=\${JOB_TTL_MINUTES}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:6020/health')"]
      interval: 10s
      timeout: 10s
      retries: ${APP_RETRIES}
      start_period: 15s
      start_interval: 1s

METRICS_API

# Add volumes section
if [ "$DEV_MODE" = true ]; then
    cat >> "$OUTPUT_FILE" << VOLUMES
volumes:
  ${RABBITMQ_VOLUME}:
VOLUMES
else
    cat >> "$OUTPUT_FILE" << VOLUMES
volumes:
  tiles_data:
  s3_data:
  ${RABBITMQ_VOLUME}:
VOLUMES
fi

echo -e "${GREEN}Generated $OUTPUT_FILE with $NUM_WORKERS worker(s) [${MODE_LABEL}]${NC}"
