name: Run tests

on:
  push:
    branches-ignore:
      - 'main'
  pull_request:
    branches-ignore:
      - 'main'
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.3'

    - name: Setup Poetry
      run: pip install poetry &&  poetry config virtualenvs.create false

    - name: Install dependencies
      run: poetry install --no-root --no-ansi

    - name: Create reports directory
      run: mkdir -p reports

    - name: Run tests
      run: poetry run pytest tests/ -m "not skip" --color=yes --junitxml=reports/junit_report.xml --cov=src --cov-report term --cov-report html:reports/coverage -W ignore::DeprecationWarning
